[#1] Add -l and GIT_CHECK_LOG_CMD
The script doesn't yet provide a fancily formatted 'git log', but at least
it doesn't break for anybody else but me, and it's now configurable

diff --git a/git-check b/git-check
--- a/git-check
+++ b/git-check
@@ -7,10 +7,16 @@
 # SPDX-License-Identifier: Unlicense
 #
 
+# Default command to use to list commits
+LOG="${GIT_CHECK_LOG_CMD:="log --oneline"}"
+
 show_help() {
-    echo "Usage: git check [-h] [reference]"
+    echo "Usage: git check [-h] [-l command] [reference]"
     echo
     echo "  -h     Show this help message"
+    echo "  -l     Command to use to log the commits"
+    echo "         Initialized from environment variable GIT_CHECK_LOG_CMD"
+    echo "         Defaults to '$LOG'"
     echo
     echo "Example: git check aa89ff6"
     echo ""
@@ -19,18 +25,26 @@ show_help() {
 
 }
 
-while getopts ":h" opt; do
+while getopts ":hl:" opt; do
   case ${opt} in
     h)
-      show_help
-      exit 0
-      ;;
-    ?)
-      echo "Invalid option: -${OPTARG}."
-      exit 1
-      ;;
+        show_help
+        exit 0
+        ;;
+    l)
+        LOG=$OPTARG
+        ;;
+    \?)
+        echo "Invalid option: -${OPTARG}."
+        exit 1
+        ;;
+    :)
+        echo "Invalid option: -$OPTARG requires an argument"
+        show_help
+        exit 1
   esac
 done
+shift $((OPTIND -1))
 
 if test $# -gt 1; then
     echo "Too many arguments: '$*'"
@@ -113,8 +127,8 @@ if test "$current_id" == "$common_ancestor"; then
     fi
 else
     echo "$current is based on $base_branch ($common_ancestor):"
-    git hist $common_ancestor..$current
-    git hist -1 $common_ancestor
+    git $LOG $common_ancestor..$current
+    git $LOG -1 $common_ancestor
     echo "Modified files:"
     git diff --name-status $common_ancestor..$current
 fi
